"""
Cost Report Generator - Produces audit-ready cost optimization reports.

Generates reports in multiple formats:
- Console (colored terminal output)
- JSON (machine-readable)
- HTML (shareable dashboard)
- CSV (spreadsheet-friendly)
"""

import csv
import io
import json
import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from .scanner import ScanResult, Finding, WasteCategory

logger = logging.getLogger(__name__)


class ReportGenerator:
    """Generates cost optimization reports from scan results."""

    SEVERITY_COLORS = {
        "high": "\033[91m",    # Red
        "medium": "\033[93m",  # Yellow
        "low": "\033[94m",     # Blue
    }
    RESET = "\033[0m"
    BOLD = "\033[1m"

    def __init__(self, scan_result: ScanResult):
        self.result = scan_result

    def generate_console_report(self) -> str:
        """Generate a colored console report."""
        lines = []
        b, r = self.BOLD, self.RESET

        lines.append(f"\n{b}{'='*70}{r}")
        lines.append(f"{b}  AZURE COST OPTIMIZATION REPORT{r}")
        lines.append(f"{b}{'='*70}{r}")
        lines.append(f"  Subscription: {self.result.subscription_name}")
        lines.append(f"  Subscription ID: {self.result.subscription_id}")
        lines.append(f"  Scan Time: {self.result.scan_timestamp}")
        lines.append(f"{b}{'='*70}{r}\n")

        # Summary
        lines.append(f"{b}  SUMMARY{r}")
        lines.append(f"  {'─'*40}")
        lines.append(f"  Total Findings: {len(self.result.findings)}")
        lines.append(
            f"  Estimated Monthly Waste: {b}${self.result.total_monthly_waste:,.2f}{r}"
        )
        lines.append(
            f"  Estimated Annual Waste: {b}${self.result.total_monthly_waste * 12:,.2f}{r}"
        )

        # Breakdown by category
        categories = {}
        for f in self.result.findings:
            cat = f.category.value
            if cat not in categories:
                categories[cat] = {"count": 0, "savings": 0}
            categories[cat]["count"] += 1
            categories[cat]["savings"] += f.estimated_savings_monthly

        lines.append(f"\n{b}  BREAKDOWN BY CATEGORY{r}")
        lines.append(f"  {'─'*40}")
        for cat, info in sorted(categories.items(), key=lambda x: -x[1]["savings"]):
            label = cat.replace("_", " ").title()
            lines.append(
                f"  {label}: {info['count']} finding(s) — ${info['savings']:,.2f}/month"
            )

        # Breakdown by severity
        severities = {"high": [], "medium": [], "low": []}
        for f in self.result.findings:
            severities[f.severity].append(f)

        lines.append(f"\n{b}  BREAKDOWN BY SEVERITY{r}")
        lines.append(f"  {'─'*40}")
        for sev in ["high", "medium", "low"]:
            color = self.SEVERITY_COLORS[sev]
            count = len(severities[sev])
            total = sum(f.estimated_savings_monthly for f in severities[sev])
            lines.append(f"  {color}■{r} {sev.upper()}: {count} finding(s) — ${total:,.2f}/month")

        # Detailed Findings
        lines.append(f"\n{b}  DETAILED FINDINGS{r}")
        lines.append(f"  {'─'*40}")

        for i, f in enumerate(
            sorted(self.result.findings, key=lambda x: -x.estimated_savings_monthly), 1
        ):
            color = self.SEVERITY_COLORS[f.severity]
            lines.append(f"\n  {b}#{i}{r} [{color}{f.severity.upper()}{r}] {f.resource_name}")
            lines.append(f"     Category: {f.category.value.replace('_', ' ').title()}")
            lines.append(f"     Resource Group: {f.resource_group}")
            lines.append(f"     Current Cost: ${f.current_cost_monthly:,.2f}/month")
            lines.append(
                f"     Potential Savings: {b}${f.estimated_savings_monthly:,.2f}/month{r}"
            )
            lines.append(f"     Recommendation: {f.recommendation}")

        # Errors
        if self.result.errors:
            lines.append(f"\n{b}  ERRORS{r}")
            lines.append(f"  {'─'*40}")
            for err in self.result.errors:
                lines.append(f"  ⚠ {err}")

        lines.append(f"\n{b}{'='*70}{r}")
        lines.append(f"  Report generated by Azure Cost Optimizer v1.0.0")
        lines.append(f"  https://github.com/AkshaykumarGlasswala/azure-cost-optimizer")
        lines.append(f"{b}{'='*70}{r}\n")

        return "\n".join(lines)

    def generate_json_report(self) -> str:
        """Generate a JSON report."""
        report = {
            "meta": {
                "tool": "Azure Cost Optimizer",
                "version": "1.0.0",
                "generated_at": datetime.now(timezone.utc).isoformat(),
            },
            "subscription": {
                "id": self.result.subscription_id,
                "name": self.result.subscription_name,
            },
            "summary": {
                "total_findings": len(self.result.findings),
                "total_monthly_waste": round(self.result.total_monthly_waste, 2),
                "total_annual_waste": round(self.result.total_monthly_waste * 12, 2),
                "by_severity": self._count_by_severity(),
                "by_category": self._count_by_category(),
            },
            "findings": [self._finding_to_dict(f) for f in self.result.findings],
            "errors": self.result.errors,
        }
        return json.dumps(report, indent=2)

    def generate_csv_report(self) -> str:
        """Generate a CSV report."""
        output = io.StringIO()
        writer = csv.writer(output)

        writer.writerow([
            "Resource Name", "Resource Group", "Category", "Severity",
            "Current Cost ($/month)", "Estimated Savings ($/month)",
            "Recommendation", "Resource ID",
        ])

        for f in sorted(self.result.findings, key=lambda x: -x.estimated_savings_monthly):
            writer.writerow([
                f.resource_name,
                f.resource_group,
                f.category.value.replace("_", " ").title(),
                f.severity.upper(),
                f"{f.current_cost_monthly:.2f}",
                f"{f.estimated_savings_monthly:.2f}",
                f.recommendation,
                f.resource_id,
            ])

        return output.getvalue()

    def generate_html_report(self) -> str:
        """Generate a standalone HTML report."""
        findings_rows = ""
        for f in sorted(self.result.findings, key=lambda x: -x.estimated_savings_monthly):
            sev_class = f"severity-{f.severity}"
            findings_rows += f"""
            <tr class="{sev_class}">
                <td>{f.resource_name}</td>
                <td>{f.resource_group}</td>
                <td>{f.category.value.replace('_', ' ').title()}</td>
                <td><span class="badge {sev_class}">{f.severity.upper()}</span></td>
                <td class="money">${f.current_cost_monthly:,.2f}</td>
                <td class="money savings">${f.estimated_savings_monthly:,.2f}</td>
                <td>{f.recommendation}</td>
            </tr>"""

        by_severity = self._count_by_severity()
        by_category = self._count_by_category()

        category_rows = ""
        for cat, info in sorted(by_category.items(), key=lambda x: -x[1]["savings"]):
            category_rows += f"""
            <tr>
                <td>{cat.replace('_', ' ').title()}</td>
                <td>{info['count']}</td>
                <td class="money">${info['savings']:,.2f}</td>
            </tr>"""

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Azure Cost Optimization Report</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #f5f7fa; color: #333; }}
        .container {{ max-width: 1200px; margin: 0 auto; padding: 20px; }}
        h1 {{ color: #0078d4; margin-bottom: 5px; }}
        .subtitle {{ color: #666; margin-bottom: 20px; }}
        .cards {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 15px; margin: 20px 0; }}
        .card {{ background: white; border-radius: 8px; padding: 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }}
        .card h3 {{ color: #666; font-size: 0.9em; text-transform: uppercase; margin-bottom: 5px; }}
        .card .value {{ font-size: 2em; font-weight: bold; color: #0078d4; }}
        .card .value.danger {{ color: #e74c3c; }}
        table {{ width: 100%; border-collapse: collapse; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 2px 4px rgba(0,0,0,0.1); margin: 20px 0; }}
        th {{ background: #0078d4; color: white; padding: 12px 15px; text-align: left; font-weight: 600; }}
        td {{ padding: 10px 15px; border-bottom: 1px solid #eee; }}
        tr:hover {{ background: #f0f7ff; }}
        .badge {{ padding: 3px 8px; border-radius: 4px; font-size: 0.8em; font-weight: bold; }}
        .badge.severity-high {{ background: #fde8e8; color: #e74c3c; }}
        .badge.severity-medium {{ background: #fef3cd; color: #856404; }}
        .badge.severity-low {{ background: #d6eaf8; color: #2471a3; }}
        .money {{ font-family: monospace; }}
        .savings {{ color: #27ae60; font-weight: bold; }}
        h2 {{ margin: 30px 0 10px; color: #333; }}
        .footer {{ text-align: center; color: #999; margin-top: 40px; padding: 20px; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>Azure Cost Optimization Report</h1>
        <p class="subtitle">
            Subscription: {self.result.subscription_name} ({self.result.subscription_id})<br>
            Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}
        </p>

        <div class="cards">
            <div class="card">
                <h3>Total Findings</h3>
                <div class="value">{len(self.result.findings)}</div>
            </div>
            <div class="card">
                <h3>Monthly Waste</h3>
                <div class="value danger">${self.result.total_monthly_waste:,.2f}</div>
            </div>
            <div class="card">
                <h3>Annual Waste</h3>
                <div class="value danger">${self.result.total_monthly_waste * 12:,.2f}</div>
            </div>
            <div class="card">
                <h3>High Severity</h3>
                <div class="value">{by_severity.get('high', {{}}).get('count', 0)}</div>
            </div>
        </div>

        <h2>Findings by Category</h2>
        <table>
            <thead><tr><th>Category</th><th>Count</th><th>Monthly Savings</th></tr></thead>
            <tbody>{category_rows}</tbody>
        </table>

        <h2>All Findings</h2>
        <table>
            <thead>
                <tr>
                    <th>Resource</th><th>Resource Group</th><th>Category</th>
                    <th>Severity</th><th>Cost/Month</th><th>Savings/Month</th><th>Recommendation</th>
                </tr>
            </thead>
            <tbody>{findings_rows}</tbody>
        </table>

        <div class="footer">
            <p>Generated by <strong>Azure Cost Optimizer v1.0.0</strong></p>
            <p>https://github.com/AkshaykumarGlasswala/azure-cost-optimizer</p>
        </div>
    </div>
</body>
</html>"""
        return html

    def save_report(self, output_dir: str = ".", formats: Optional[list[str]] = None):
        """Save reports in specified formats."""
        formats = formats or ["json", "html", "csv"]
        output_path = Path(output_dir)
        output_path.mkdir(parents=True, exist_ok=True)

        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        saved = []

        if "console" in formats:
            print(self.generate_console_report())

        if "json" in formats:
            path = output_path / f"cost_report_{timestamp}.json"
            path.write_text(self.generate_json_report())
            saved.append(str(path))
            logger.info(f"JSON report saved: {path}")

        if "html" in formats:
            path = output_path / f"cost_report_{timestamp}.html"
            path.write_text(self.generate_html_report())
            saved.append(str(path))
            logger.info(f"HTML report saved: {path}")

        if "csv" in formats:
            path = output_path / f"cost_report_{timestamp}.csv"
            path.write_text(self.generate_csv_report())
            saved.append(str(path))
            logger.info(f"CSV report saved: {path}")

        return saved

    def _count_by_severity(self) -> dict:
        result = {}
        for f in self.result.findings:
            if f.severity not in result:
                result[f.severity] = {"count": 0, "savings": 0}
            result[f.severity]["count"] += 1
            result[f.severity]["savings"] += f.estimated_savings_monthly
        return result

    def _count_by_category(self) -> dict:
        result = {}
        for f in self.result.findings:
            cat = f.category.value
            if cat not in result:
                result[cat] = {"count": 0, "savings": 0}
            result[cat]["count"] += 1
            result[cat]["savings"] += f.estimated_savings_monthly
        return result

    @staticmethod
    def _finding_to_dict(f: Finding) -> dict:
        return {
            "resource_id": f.resource_id,
            "resource_name": f.resource_name,
            "resource_group": f.resource_group,
            "category": f.category.value,
            "severity": f.severity,
            "current_cost_monthly": round(f.current_cost_monthly, 2),
            "estimated_savings_monthly": round(f.estimated_savings_monthly, 2),
            "recommendation": f.recommendation,
            "details": f.details,
            "timestamp": f.timestamp,
        }
